// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcArmsDfkXibTXW1ObRjY24C1zLuyWC5k',
    appId: '1:121884000730:web:4666b508a7ba09327580e3',
    messagingSenderId: '121884000730',
    projectId: 'chat-app-772b7',
    authDomain: 'chat-app-772b7.firebaseapp.com',
    storageBucket: 'chat-app-772b7.appspot.com',
    measurementId: 'G-WFG7SJZCKT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0N0n7j8tuPZ8vqxeTppYpjvhXohf73G4',
    appId: '1:121884000730:android:0ed9b8cc9578008a7580e3',
    messagingSenderId: '121884000730',
    projectId: 'chat-app-772b7',
    storageBucket: 'chat-app-772b7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy-2WenD0X-x82JKR_VoBPGn4RnKy_YQQ',
    appId: '1:121884000730:ios:426e5bc188b3fd627580e3',
    messagingSenderId: '121884000730',
    projectId: 'chat-app-772b7',
    storageBucket: 'chat-app-772b7.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAy-2WenD0X-x82JKR_VoBPGn4RnKy_YQQ',
    appId: '1:121884000730:ios:9fbca344bc1815927580e3',
    messagingSenderId: '121884000730',
    projectId: 'chat-app-772b7',
    storageBucket: 'chat-app-772b7.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
